name: tensorGPU
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2020.6.20
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.0
  - cycler=0.11.0
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.3.3
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9b
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libtiff=4.0.8
  - libwebp=1.2.2
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandas=1.2.3
  - patsy=0.5.3
  - pillow=9.3.0
  - ply=3.11
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyqt5-sip=4.19.18
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2023.3.post1
  - pyyaml=6.0
  - qt=5.9.7
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=59.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - statsmodels=0.13.5
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.6.0
  - termcolor=2.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.7
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.2
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.14.1
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - pip:
      - numpy==1.18.5
      - pip==23.3.1
      - protobuf==3.19.6
      - scipy==1.4.1
      - tensorflow-gpu==2.3.0
      - tensorflow-gpu-estimator==2.3.0
